dist: trusty

sudo: true

services:
  - docker

os:
  - linux
  - osx

language: go
go: 1.14.x

addons:
  apt:
    packages:
      - make

before_install:
  - bash ./scripts/travis_ssh.sh

script:
  - ./scripts/travis-ci.sh

after_success:
  # Run uploads only on non-PRs since PRs sent from forked repositories do not have access to encrypted variables
  # Also run uploads only on staging and master branches
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && ([ "$TRAVIS_BRANCH" = "master" ] || [ "$TRAVIS_BRANCH" = "staging" ]); then bash ./scripts/upload_nightlies.sh $TRAVIS_BRANCH; fi
