# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on: [push, pull_request]

jobs:
  linux-docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Run CI script
        run: ./scripts/travis-ci.sh
        env:
          TRAVIS_OS_NAME: linux
          TRAVIS_BUILD_DIR: ${{github.workspace}}
  macos:
    runs-on: macos-10.15
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Run CI script
        run: ./scripts/travis-ci.sh
        env:
          TRAVIS_OS_NAME: osx
          TRAVIS_BUILD_DIR: ${{github.workspace}}
